name: Run Conda Env, Pytest for integegrative test

on:
  push:
    branches: [ 1.5.0 ]
    paths: # the job will run when these files pushed
      - '**.py'
      - '**.sh'
      - '**.yml'
      - 'conda/**'
jobs:
  test-integration-default:
    name: Default settings
    # step 1): setup OS
    runs-on: ubuntu-latest
    steps:
      # step 2): checkout repo
      - uses: actions/checkout@v3
      # step 3): setup python
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Check Python version
        run: |
          python --version
      # step 4): setup conda
      - name: Run setup-conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
      # step 5): setup cuda
      - name: Setup Cuda
        uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit
        with:
          cuda: '11.5.1'
      # step 6): create conda env, pip install
      - name: Create conda env
        run: |
          # step 7): create env using AMPL package list
          conda create -y -n TEST python=3.7 --file conda/conda_package_list.txt
          source activate TEST
          conda info --envs
          # step 8): pip install AMPL package list
          python -m pip install --upgrade pip
          pip install -r conda/pip_requirements.txt
          # step 9): fix the keras issues
          pip uninstall -y keras
          pip install -U tensorflow keras
          # step 10): build 
          ./build.sh && ./install_dev.sh
          # step 11): run test 
          cd atomsci/ddm/test/integrative
          bash integrative_batch_tests.sh
